In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('LDP_4-CompRadHrlySummary_2015.csv', parse_dates=['DateTime'])
df1 = pd.read_csv('LDP_4CompRadHrlySummary_2019.csv', parse_dates=['DateTime'])
df2 = pd.read_csv('LDP_HrlySummary_2015.csv', parse_dates=['DateTime'])
df3 = pd.read_csv('LDP_HrlySummary_2019.csv', parse_dates=['DateTime'])
df4 = pd.read_csv('LDP_SoilHrlySummary_2019.csv', parse_dates=['DateTime'])

In [3]:
np.array(df['SWin-W/m2']).astype("float64")
np.array(df['SWout-W/m2']).astype("float64")
np.array(df['LWin-W/m2']).astype("float64")
np.array(df['LWout-W/m2']).astype("float64")

array([238.49, 235.93, 240.58, ..., 248.98, 249.91, 252.13])

In [4]:
np.array(df1['SWin-W/m2']).astype("float64")
np.array(df1['SWout-W/m2']).astype("float64")
np.array(df1['LWin-W/m2']).astype("float64")
np.array(df1['LWout-W/m2']).astype("float64")

array([229.8, 227.2, 223.7, ..., 307.9, 308.3, 310.2])

In [5]:
np.array(df2['AirTemperature-C']).astype("float64")
np.array(df2['NetRadiation-Watts/m2']).astype("float64")
np.array(df2['RelativeHumidity-%']).astype("float64")
np.array(df2['WindSpeed-m/s']).astype("float64")

array([0.55, 0.68, 0.65, ..., 2.71, 3.25, 3.51])

In [6]:
np.array(df3['AirTemperature_C']).astype("float64")
np.array(df3['NetRadiation_W/m2']).astype("float64")
np.array(df3['RelativeHumidity_percent']).astype("float64")
np.array(df3['WindSpeed_m/s']).astype("float64")

array([-6.999e+03, -6.999e+03, -6.999e+03, ...,  1.020e+00,  1.110e+00,
        1.470e+00])

In [7]:
np.array(df4['SoilMoisturePit1-vol']).astype("float64")
np.array(df4['SoilMoisturePit2-vol']).astype("float64")

array([0.141, 0.141, 0.141, ..., 0.132, 0.132, 0.132])

In [8]:
filtered_df = df.loc[(df['DateTime'] >= '2015-05-01 00:00:00')
                     & (df['DateTime'] < '2015-05-01 23:00:00')]

In [9]:
filtered_df1 = df.loc[(df1['DateTime'] >= '2019-05-01 00:00:00')
                     & (df1['DateTime'] < '2019-05-01 23:00:00')]

In [10]:
filtered_df2 = df.loc[(df2['DateTime'] >= '2015-05-01 00:00:00')
                     & (df2['DateTime'] < '2015-05-01 23:00:00')]

In [11]:
filtered_df3 = df.loc[(df3['DateTime'] >= '2019-05-01 0:00:00')
                     & (df3['DateTime'] < '2019-05-01 23:00:00')] 

In [12]:
filtered_df4 = df.loc[(df4['DateTime'] >= '2019-05-01 0:00:00')
                     & (df4['DateTime'] < '2019-05-01 23:00:00')]

In [13]:
shortwave_in_2015 = filtered_df['SWin-W/m2']
shortwave_out_2015 = filtered_df['SWout-W/m2']
shortwave_2015 = shortwave_in_2015-shortwave_out_2015

In [14]:
shortwave_in_2019 = filtered_df1['SWin-W/m2']
shortwave_out_2019 = filtered_df1['SWout-W/m2']
shortwave_2019 = shortwave_in_2019-shortwave_out_2019

In [15]:
longwave_in_2015 = filtered_df['LWin-W/m2']
longwave_out_2015 = filtered_df['LWout-W/m2']
longwave_2015 = longwave_in_2015-longwave_out_2015 

In [16]:
longwave_in_2019 = filtered_df1['LWin-W/m2']
longwave_out_2019 = filtered_df1['LWout-W/m2']
longwave_2019 = longwave_in_2019-longwave_in_2019

In [17]:
AE_2015 = shortwave_2015-longwave_2015
AE1_2015 = shortwave_2015+longwave_2015

In [18]:
AE_2019 = shortwave_2019-longwave_2019
AE1_2019 = shortwave_2019+longwave_2019

In [19]:
Air_Temp_C_2015 = filtered_df2['AirTemperature-C']
Net_Rad_2015 = filtered_df2['NetRadiation-Watts/m2']
Relative_Humid_2015 = filtered_df2['RelativeHumidity-%']
Wind_Speed_2015 = filtered_df2['WindSpeed-m/s']

KeyError: 'AirTemperature-C'

In [ ]:
Air_Temp_C_2019 = filtered_df3['AirTemperature_C']
Net_Rad_2019 = filtered_df3['NetRadiation_W/m2']
Relative_Humid_2019 = filtered_df3['RelativeHumidity_percent']
Wind_Speed_2019 = filtered_df3['WindSpeed_m/s']

In [ ]:
Soil_Moisture_1 = filtered_df4['SoilMoisturePit1-vol']
Soil_Moisture_2 = filtered_df4['SoilMoisturePit2-vol']

In [ ]:
y = AE_2015  
x = filtered_df['DateTime'] 
plt.style.use('ggplot')
plt.title('AE over time', color='black')
plt.xlabel('Year', color='black')
plt.ylabel('Availaible Energy', color='black')  
plt.plot(x, y, ':')
plt.show()  

In [ ]:
y = AE1_2015  
x = filtered_df['DateTime'] 
plt.style.use('ggplot')
plt.title('AE over time', color='black')
plt.xlabel('Year', color='black')
plt.ylabel('Availaible Energy', color='black')  
plt.plot(x, y, ':')  
plt.show() 

In [ ]:
y = AE1_2019 
x = filtered_df1['DateTime'] 
plt.style.use('ggplot')
plt.title('AE over time', color='black')
plt.xlabel('Year', color='black')
plt.ylabel('Availaible Energy', color='black')  
plt.plot(x, y)  
plt.show() 

In [ ]:
y = Air_Temp_C_2015 
x = filtered_df2['DateTime'] 
plt.style.use('ggplot')
plt.title('Air Temperature over time', color='black')
plt.xlabel('Year', color='black')
plt.ylabel('Availaible Energy', color='black')  
plt.plot(x, y)  
plt.show() 

In [ ]:
#y = Net_Rad_2015
#x = filtered_df2['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Net Radiation over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Net Radiation', color='black')  
#plt.plot(x, y)  
#plt.show() 

In [ ]:
#y = Relative_Humid_2015
#x = filtered_df2['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Relative Humidity over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Reative Humidity', color='black')  
#plt.plot(x, y)  
#plt.show()

In [ ]:
#y = Wind_Speed_2015
#x = filtered_df2['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Wind Speed over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Wind Speed', color='black')  
#plt.plot(x, y)  
#plt.show()

In [ ]:
#y = Air_Temp_C_2019
#x = filtered_df3['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Air Temperature over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Air Temperature', color='black')  
#plt.plot(x, y)  
#plt.show()

In [ ]:
#y = Net_Rad_2019
#x = filtered_df3['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Net Radiation over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Net Radiation', color='black')  
#plt.plot(x, y)  
#plt.show()

In [ ]:
#y = Relative_Humid_2019
#x = filtered_df3['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Relative Humidity over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Relative Humidity', color='black')  
#plt.plot(x, y)  
#plt.show()

In [ ]:
#y = Wind_Speed_2019
#x = filtered_df3['DateTime'] 
#plt.style.use('ggplot')
#plt.title('Wind Speed over time', color='black')
#plt.xlabel('Year', color='black')
#plt.ylabel('Wind Speed', color='black')  
#plt.plot(x, y)  
#plt.show()